@echo off
echo Starting LensAudit...
echo Checking for node_modules...
if not exist "node_modules\" (
    echo Installing dependencies...
    call npm install
)
echo Starting development server...
call npm run dev
pause
